### ISSUE TITLE
server/V2 crashes with "slice bounds out of range"

### ISSUE THREAD

**Issue by talaniz** [quii/learn-go-with-tests#274]
```
go version
go version go1.13.1 darwin/amd64
```

To reproduce:
Combine server.go & main.go (otherwise "./main.go:17:13: undefined: PlayerServer")
Run `go run main.go`
Expected result: navigating to http://localhost:5000/{Floyd|Oliver} returns 123
Result:

```
2019/10/23 10:11:10 http: panic serving [::1]:51306: runtime error: slice bounds out of range [9:7]
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000126000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc000154060)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc000160000, 0xc00014e000)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc000160000, 0xc00014e000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000126000, 0x1363700, 0xc0000e6280)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:10 http: panic serving [::1]:51307: runtime error: slice bounds out of range [9:7]
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc0001260a0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc0000d6120)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc00010e0e0, 0xc000152000)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc00010e0e0, 0xc000152000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001260a0, 0x1363700, 0xc00008e040)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:10 http: panic serving [::1]:51310: runtime error: slice bounds out of range [9:7]
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc0001860a0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc00001a300)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc0001b6000, 0xc00014e100)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc0001b6000, 0xc00014e100)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001860a0, 0x1363700, 0xc0000e63c0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:10 http: panic serving [::1]:51311: runtime error: slice bounds out of range [9:7]
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc000186140)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc0000d61c0)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc00010e1c0, 0xc0001d4000)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc00010e1c0, 0xc0001d4000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000186140, 0x1363700, 0xc00011c040)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:10 http: panic serving [::1]:51312: runtime error: slice bounds out of range [9:7]
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc0001861e0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc000154120)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc0001600e0, 0xc0001d6000)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc0001600e0, 0xc0001d6000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001861e0, 0x1363700, 0xc00008e180)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:10 http: panic serving [::1]:51315: runtime error: slice bounds out of range [9:7]
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc000126140)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc0001541a0)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc0001601c0, 0xc0001d6100)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc0001601c0, 0xc0001d6100)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000126140, 0x1363700, 0xc00008e280)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:15 http: panic serving [::1]:51316: runtime error: slice bounds out of range [9:7]
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc0000d0aa0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc000154220)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc0001602a0, 0xc0001d6200)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc0001602a0, 0xc0001d6200)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000d0aa0, 0x1363700, 0xc00008e3c0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:15 http: panic serving [::1]:51317: runtime error: slice bounds out of range [9:7]
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc0001261e0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc00001a3a0)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc0001b60e0, 0xc00014e200)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc0001b60e0, 0xc00014e200)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001261e0, 0x1363700, 0xc0000e64c0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/23 10:11:15 http: panic serving [::1]:51320: runtime error: slice bounds out of range [9:7]
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc00022c000)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x12d95a0, 0xc00022e060)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
main.(*PlayerServer).ServeHTTP(0xc0000b8af0, 0x1363180, 0xc00023c000, 0xc0001d4100)
        /Users/talaniz/gocode/src/github.com/talaniz/golang-tdd-proj/main.go:20 +0x141
net/http.serverHandler.ServeHTTP(0xc00010e000, 0x1363180, 0xc00023c000, 0xc0001d4100)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00022c000, 0x1363700, 0xc00011c100)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
```

**Comment by talaniz** [comment]
For good order, here's the main.go contents:
```
package main

import (
	"fmt"
	"log"
	"net/http"
)

// PlayerStore stores score information about players
type PlayerStore interface {
	GetPlayerScore(name string) int
}

// PlayerServer is a HTTP interface for player information
type PlayerServer struct {
	store PlayerStore
}

func (p *PlayerServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	player := r.URL.Path[len("/players/"):]

	score := p.store.GetPlayerScore(player)

	if score == 0 {
		w.WriteHeader(http.StatusNotFound)
	}

	fmt.Fprint(w, score)
}

// InMemoryPlayerStore collects data about players in memory
type InMemoryPlayerStore struct{}

// GetPlayerScore retrieves scores for a given player
func (i *InMemoryPlayerStore) GetPlayerScore(name string) int {
	return 123
}

func main() {
	server := &PlayerServer{&InMemoryPlayerStore{}}

	if err := http.ListenAndServe(":5000", server); err != nil {
		log.Fatalf("could not listen on port 5000 %v", err)
	}
}
```

**Comment by denisbrodbeck** [comment]
> Run `go run main.go`
> Expected result: navigating to [http://localhost:5000/{Floyd|Oliver}](http://localhost:5000/%7BFloyd%7COliver%7D) returns 123
> Result: crash

You'll want to call [http://localhost:5000/players/{Floyd|Oliver}](http://localhost:5000/players/%7BFloyd%7COliver%7D) and __not__ [http://localhost:5000/{Floyd|Oliver}](http://localhost:5000/%7BFloyd%7COliver%7D).

At this point of your code you're more or less enforcing that all incoming requests go to `http://localhost:5000/players/xyz` or fail horribly :smiley: There's no error handling / corrective behaviour for all other possible cases (different/empty path/route) in your request handler, yet.

Just follow the [tutorial](https://quii.gitbook.io/learn-go-with-tests/build-an-application/json) and you'll get there :smirk:

**Comment by talaniz** [comment]
Thanks for this. I was thinking about it over the weekend and knew it wasn't necessarily going to run perfectly given the state of the application. This morning, before seeing this, I came back to it again and realized I forgot the /players/ portion of the URL. 🤦‍♂ Closing out.
